# Generated by Django 5.2.16 on 2026-07-28 04:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('color', models.CharField(default='#10b981', help_text='HEX rang', max_length=7)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_uz', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], db_index=True, default='easy', max_length=8)),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=12)),
                ('description_uz', models.TextField(help_text='Markdown')),
                ('description_en', models.TextField(blank=True, help_text='Markdown')),
                ('constraints_uz', models.TextField(blank=True)),
                ('constraints_en', models.TextField(blank=True)),
                ('hint_uz', models.TextField(blank=True)),
                ('hint_en', models.TextField(blank=True)),
                ('editorial_uz', models.TextField(blank=True)),
                ('editorial_en', models.TextField(blank=True)),
                ('starter_code_python', models.TextField(blank=True)),
                ('starter_code_javascript', models.TextField(blank=True)),
                ('starter_code_cpp', models.TextField(blank=True)),
                ('solution_code_python', models.TextField(blank=True, help_text='Ichki foydalanish uchun etalon yechim')),
                ('time_limit_ms', models.PositiveIntegerField(default=2000)),
                ('memory_limit_kb', models.PositiveIntegerField(default=262144)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_contest_only', models.BooleanField(default=False, help_text="Contest tugagunga qadar ommaviy ro'yxatda ko'rinmaydi (11-bo'lim)")),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('accepted_submissions', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_problems', to=settings.AUTH_USER_MODEL)),
                ('companies', models.ManyToManyField(blank=True, related_name='problems', to='problems.company')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag')),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('bonus_points', models.PositiveIntegerField(default=5)),
                ('note_uz', models.CharField(blank=True, max_length=200)),
                ('note_en', models.CharField(blank=True, max_length=200)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='problems.problem')),
            ],
            options={
                'db_table': 'daily_challenges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('input', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Ochiq (namuna) test — foydalanuvchiga ko'rinadi")),
                ('explanation_uz', models.TextField(blank=True)),
                ('explanation_en', models.TextField(blank=True)),
                ('time_limit_ms', models.PositiveIntegerField(blank=True, help_text="Bo'sh bo'lsa masala limiti", null=True)),
                ('memory_limit_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, help_text='Shaxsiy izoh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='problems.problem')),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='SolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_solved_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvers', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solved_problems',
                'ordering': ['-first_solved_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status', 'difficulty'], name='problems_status_d44b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_slug_fa7e51_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem', 'is_sample'], name='test_cases_problem_ad5bcc_idx'),
        ),
    ]
