# Generated by Django 5.2.16 on 2026-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
