# Generated by Django 5.2.16 on 2026-07-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_cover_image_url_problem_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='companies',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
