# Generated by Django 5.2.16 on 2026-07-28 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('comment_reply', 'Izohga javob'), ('discussion_comment', 'Muhokamangizga izoh'), ('submission_result', 'Yechim natijasi'), ('contest_soon', 'Musobaqa yaqinlashdi'), ('contest_result', 'Musobaqa natijasi'), ('achievement', 'Yutuq'), ('group_invite', "Guruhga qo'shildingiz"), ('moderation', 'Moderatsiya qarori'), ('account', 'Hisob'), ('announcement', "E'lon")], db_index=True, default='account', max_length=24)),
                ('level', models.CharField(choices=[('info', "Ma'lumot"), ('success', 'Muvaffaqiyat'), ('warning', 'Ogohlantirish'), ('danger', 'Muhim')], default='info', max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('url', models.CharField(blank=True, help_text='Frontend ichidagi nisbiy havola', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text="Harakatni bajargan foydalanuvchi (bo'lsa)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx')],
            },
        ),
    ]
