# Generated by Django 5.2.16 on 2026-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('source_lang', models.CharField(default='uz', max_length=8)),
                ('target_lang', models.CharField(db_index=True, default='en', max_length=8)),
                ('source_text', models.TextField(blank=True)),
                ('translated_text', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'translation_cache',
                'indexes': [models.Index(fields=['target_lang', 'created_at'], name='translation_target__6c5a5a_idx')],
            },
        ),
    ]
