# Generated by Django 5.2.16 on 2026-07-28 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentvote'),
        ('problems', '0003_problem_cover_image_url_problem_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'Yangilik')], db_index=True, default='blog', max_length=8),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['kind', 'status', '-published_at'], name='articles_kind_fd40bc_idx'),
        ),
    ]
