# Generated by Django 5.2.16 on 2026-07-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_articles_news_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
