# Generated by Django 5.2.16 on 2026-07-30 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_delete_article'),
        ('problems', '0004_remove_problem_companies_delete_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='problem',
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.discussion'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['problem', 'status', 'created_at'], name='comments_problem_1921f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discussion__isnull', False), ('problem__isnull', True)), models.Q(('discussion__isnull', True), ('problem__isnull', False)), _connector='OR'), name='comment_belongs_to_one_target'),
        ),
    ]
