# Generated by Django 5.2.16 on 2026-07-28 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_uz', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('description_uz', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('running', 'Davom etmoqda'), ('finished', 'Tugagan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='draft', max_length=12)),
                ('visibility', models.CharField(choices=[('public', 'Ochiq'), ('private', 'Yopiq (parol bilan)')], default='public', max_length=10)),
                ('access_password', models.CharField(blank=True, max_length=64)),
                ('is_rated', models.BooleanField(default=True, help_text="Reyting o'zgaradimi (7-bo'lim)")),
                ('is_virtual_allowed', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_k_new', models.PositiveIntegerField(default=40, help_text='Yangi userlar uchun K')),
                ('rating_k_experienced', models.PositiveIntegerField(default=20)),
                ('plagiarism_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ratings_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contests',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0, help_text='Daqiqalarda')),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('rating_before', models.IntegerField(blank=True, null=True)),
                ('rating_after', models.IntegerField(blank=True, null=True)),
                ('rating_change', models.IntegerField(default=0)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('disqualify_reason', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_participants',
                'ordering': ['rank', '-score', 'penalty'],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, help_text='A, B, C ...', max_length=4)),
                ('points', models.PositiveIntegerField(default=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='problems.problem')),
            ],
            options={
                'db_table': 'contest_problems',
                'ordering': ['order'],
                'unique_together': {('contest', 'problem')},
            },
        ),
    ]
