# Generated by Django 5.2.16 on 2026-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_deleted_at_contest_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
