# Generated by Django 5.2.16 on 2026-07-28 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('judge', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('body_uz', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', "Ma'lumot"), ('success', 'Muvaffaqiyat'), ('warning', 'Ogohlantirish'), ('danger', 'Muhim')], default='info', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('value_type', models.CharField(choices=[('string', 'Matn'), ('number', 'Raqam'), ('boolean', "Ha/Yo'q"), ('json', 'JSON'), ('text', 'Uzun matn')], default='string', max_length=10)),
                ('group', models.CharField(choices=[('general', 'Umumiy'), ('judge', 'Judge'), ('security', 'Xavfsizlik'), ('content', 'Kontent'), ('rating', 'Reyting')], db_index=True, default='general', max_length=20)),
                ('label_uz', models.CharField(blank=True, max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False, help_text='Frontendga ochiq beriladimi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_settings',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismPair',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity', models.FloatField(default=0.0, help_text='0..1')),
                ('language', models.CharField(blank=True, max_length=16)),
                ('same_ip', models.BooleanField(default=False)),
                ('time_delta_seconds', models.IntegerField(blank=True, null=True)),
                ('matched_lines', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmagan"), ('cleared', "Tozalangan (yolg'on signal)"), ('confirmed', 'Tasdiqlangan')], db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_pairs', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_pairs', to='problems.problem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_as_a', to='judge.submission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_as_b', to='judge.submission')),
                ('user_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plagiarism_pairs',
                'ordering': ['-similarity', '-created_at'],
                'unique_together': {('submission_a', 'submission_b')},
            },
        ),
    ]
