# Generated by Django 5.2.16 on 2026-07-28 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_group_deleted_at_group_deleted_by'),
        ('contests', '0002_contest_deleted_at_contest_deleted_by'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='python, cpp, javascript ...', max_length=24, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('judge0_id', models.PositiveIntegerField(help_text='Judge0 language_id')),
                ('version', models.CharField(blank=True, max_length=40)),
                ('monaco_id', models.CharField(blank=True, help_text='Monaco muharriri tili', max_length=24)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('starter_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'judge_languages',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Hamma'), ('users', 'Faqat foydalanuvchilar'), ('staff', 'Admin va moderatorlar'), ('contest', 'Contest ishtirokchilari'), ('group', "Guruh a'zolari")], db_index=True, default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='email_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_email',
            field=models.BooleanField(default=False, help_text='Banner bilan birga email ham yuborilsin'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='community.group'),
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('full', "To'liq"), ('data', "Faqat ma'lumot")], default='data', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
