# Generated by Django 5.2.16 on 2026-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_level_settings_to_ranks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='action_label_en',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='announcement',
            name='action_label_uz',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='announcement',
            name='action_url',
            field=models.CharField(blank=True, help_text="Tugma manzili: sayt ichida `/contests/bahor-kubogi` yoki to'liq `https://...`", max_length=300),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_dismissible',
            field=models.BooleanField(default=True, help_text="Foydalanuvchi bannerni yopa oladimi (texnik ishlar uchun — yo'q)"),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text="Ro'yxatning eng tepasida tursin"),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notified_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_notification',
            field=models.BooleanField(default=False, help_text="Sayt ichidagi qo'ng'iroqqa ham yozilsin"),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_push',
            field=models.BooleanField(default=False, help_text="Obuna bo'lgan qurilmalarga brauzer xabari ham ketsin"),
        ),
    ]
