# Generated by Django 5.2.16 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='group',
            field=models.CharField(choices=[('general', 'Umumiy'), ('social', 'Ijtimoiy tarmoqlar'), ('judge', 'Judge'), ('security', 'Xavfsizlik'), ('content', 'Kontent'), ('rating', 'Reyting')], db_index=True, default='general', max_length=20),
        ),
    ]
