# Generated by Django 5.2.16 on 2026-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_remove_news_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
