# Generated by Django 5.2.16 on 2026-07-28 04:10

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]{3,32}$', "Username 3–32 belgidan iborat bo'lib, faqat harf, raqam va _ dan tashkil topsin.")])),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('oauth_google_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('rating', models.IntegerField(db_index=True, default=1500)),
                ('max_rating', models.IntegerField(default=1500)),
                ('total_points', models.IntegerField(db_index=True, default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('submissions_count', models.IntegerField(default=0)),
                ('contests_participated', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_solved_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('moderator', 'Moderator'), ('admin', 'Administrator')], db_index=True, default='user', max_length=16)),
                ('locale', models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English')], default='uz', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(db_index=True, default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_contest', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('verify', 'Email tasdiqlash'), ('reset', 'Parolni tiklash')], default='verify', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-total_points'], name='users_total_p_333550_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-rating'], name='users_rating_363c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_banned'], name='users_role_fa5fae_idx'),
        ),
    ]
