# Generated by Django 5.2.16 on 2026-07-28 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='denied_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Roldan olib tashlanadigan ruxsatlar'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list, help_text="Rolga qo'shimcha beriladigan ruxsatlar, masalan ['problems.delete']"),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(blank=True, max_length=80)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('is_current', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_sessions',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
