# Generated by Django 5.2.16 on 2026-07-28 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++')], db_index=True, max_length=16)),
                ('code', models.TextField()),
                ('code_length', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Navbatda'), ('JUDGING', 'Tekshirilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('WRONG_ANSWER', "Noto'g'ri javob"), ('TIME_LIMIT_EXCEEDED', 'Vaqt tugadi'), ('MEMORY_LIMIT_EXCEEDED', 'Xotira yetmadi'), ('RUNTIME_ERROR', 'Bajarilish xatosi'), ('COMPILE_ERROR', 'Kompilyatsiya xatosi'), ('SYSTEM_ERROR', 'Tizim xatosi')], db_index=True, default='PENDING', max_length=24)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('failed_test_index', models.PositiveIntegerField(blank=True, help_text='Nechanchi testda xato (1 dan boshlab)', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('compile_output', models.TextField(blank=True)),
                ('is_practice', models.BooleanField(default=True, help_text='Contestdan tashqari yechim')),
                ('is_first_accepted', models.BooleanField(default=False)),
                ('judge_tokens', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Navbatda'), ('JUDGING', 'Tekshirilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('WRONG_ANSWER', "Noto'g'ri javob"), ('TIME_LIMIT_EXCEEDED', 'Vaqt tugadi'), ('MEMORY_LIMIT_EXCEEDED', 'Xotira yetmadi'), ('RUNTIME_ERROR', 'Bajarilish xatosi'), ('COMPILE_ERROR', 'Kompilyatsiya xatosi'), ('SYSTEM_ERROR', 'Tizim xatosi')], max_length=24)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, help_text='Faqat sample testlar uchun saqlanadi')),
                ('stderr', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='judge.submission')),
                ('test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='problems.testcase')),
            ],
            options={
                'db_table': 'submission_test_results',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='submissions_user_id_1dd2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status'], name='submissions_problem_b4f4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-created_at'], name='submissions_status_51c352_idx'),
        ),
    ]
