# Generated by Django 5.2.16 on 2026-07-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_counted',
            field=models.BooleanField(default=False, help_text="Statistika hisoblagichlariga qo'shilganmi (rejudge takrorlamasligi uchun)"),
        ),
    ]
