# Generated by Django 5.2.16 on 2026-08-04 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=180)),
                ('prompt_md', models.TextField(help_text='Topshiriq sharti — Markdown')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++')], default='python', max_length=16)),
                ('starter_code', models.TextField(blank=True, help_text="Muharrirda ochiladigan boshlang'ich kod")),
                ('solution_code', models.TextField(blank=True, help_text='Namuna yechim — mashq bajarilgach ochiladi')),
                ('hint_uz', models.TextField(blank=True, help_text="Yordam — foydalanuvchi so'raganda ochiladi")),
                ('points', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_limit_ms', models.PositiveIntegerField(default=5000)),
                ('memory_limit_kb', models.PositiveIntegerField(default=262144)),
            ],
            options={
                'db_table': 'course_exercises',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_uz', models.CharField(max_length=160)),
                ('subtitle_uz', models.CharField(blank=True, help_text='Katalogdagi bir qatorli izoh', max_length=220)),
                ('description_uz', models.TextField(blank=True, help_text='Markdown — kurs sahifasidagi tavsif')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++')], db_index=True, default='python', max_length=16)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], db_index=True, default='beginner', max_length=14)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=12)),
                ('badge', models.CharField(blank=True, help_text='Kartadagi qisqa belgi: Py, JS, C++', max_length=6)),
                ('accent_color', models.CharField(blank=True, help_text='HEX rang, masalan #1e5eff', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Katalogdagi tartib')),
                ('is_featured', models.BooleanField(default=False, help_text="Katalog tepasida ajratib ko'rsatiladi")),
                ('estimated_hours', models.PositiveIntegerField(default=0, help_text="Taxminiy o'quv soati")),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_courses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['order', 'title_uz'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++')], max_length=16)),
                ('code', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_output', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_exercise_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=True, help_text="Ochiq test — foydalanuvchiga ko'rinadi va «Ishga tushirish»da ishlatiladi")),
                ('explanation_uz', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.exercise')),
            ],
            options={
                'db_table': 'course_exercise_tests',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=160)),
                ('summary_uz', models.CharField(blank=True, max_length=300)),
                ('content_md', models.TextField(blank=True, help_text='Nazariya — Markdown')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], db_index=True, default='published', max_length=12)),
                ('points', models.PositiveIntegerField(default=10, help_text='Mavzu yakunlanganda beriladigan ball')),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'db_table': 'course_lessons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson'),
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(blank=True, max_length=180)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++')], default='python', max_length=16)),
                ('code', models.TextField()),
                ('expected_output', models.TextField(blank=True, help_text='Kod nima chiqarishi kutiladi')),
                ('explanation_uz', models.TextField(blank=True, help_text='Misol ostidagi izoh — Markdown')),
                ('is_runnable', models.BooleanField(default=True, help_text="«Sinab ko'rish» tugmasi ko'rinadi")),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='courses.lesson')),
            ],
            options={
                'db_table': 'course_examples',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
                ('last_lesson', models.ForeignKey(blank=True, help_text='«Davom etish» tugmasi shu mavzuga qaytaradi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson')),
            ],
            options={
                'db_table': 'course_enrollments',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_best_score', models.PositiveIntegerField(default=0)),
                ('quiz_total', models.PositiveIntegerField(default=0)),
                ('quiz_passed_at', models.DateTimeField(blank=True, null=True)),
                ('exercises_solved', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_lesson_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=140)),
                ('summary_uz', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'db_table': 'course_modules',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_quiz_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_uz', models.TextField()),
                ('options', models.JSONField(default=list, help_text="Variantlar ro'yxati (matn massivi)")),
                ('correct_index', models.PositiveIntegerField(default=0, help_text="To'g'ri variant tartibi (0 dan)")),
                ('explanation_uz', models.TextField(blank=True, help_text="Javobdan keyin ko'rinadigan izoh")),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.lesson')),
            ],
            options={
                'db_table': 'course_quiz_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'language'], name='courses_status_377b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_slug_360be0_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'exercise', '-created_at'], name='course_exer_user_id_a462fe_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['exercise', 'is_correct'], name='course_exer_exercis_1d3685_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisetest',
            index=models.Index(fields=['exercise', 'is_sample'], name='course_exer_exercis_5bf4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'order'], name='course_exer_lesson__04dadd_idx'),
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['lesson', 'order'], name='course_exam_lesson__8ea751_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_enrollment_per_course'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='course_less_user_id_fb7d36_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_progress_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='uniq_module_slug_per_course'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'status'], name='course_less_course__392910_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='uniq_lesson_slug_per_course'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'lesson', '-created_at'], name='course_quiz_user_id_a2e207_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['lesson', 'order'], name='course_quiz_lesson__51fce7_idx'),
        ),
    ]
